"""Distributional measurement estimator — the project's core contribution (B.4).

This estimator computes the **multi-level tail-risk feedback** — six left-tail
scalars (cvar_05/10/25/01, left_tail_mass, robust_skew) — that the LLM
reward-designer is fed in the tail-feedback arm. It is a **critic-agnostic
post-hoc estimator**: it reads no Q-network and fits only on *realized* portfolio
returns (audit A-1). "Critic-agnostic" means architecture-independent (SAC mean
critic, TQC quantile critic, anything) — it does NOT mean agent-independent: the
returns it fits are the trained policy's OWN realized returns under the candidate
reward (see the endogeneity note below). It is computed on the **training-period**
realized **simple** (arithmetic, per-step) portfolio returns (audit B-2):
measuring on validation and then selecting on validation would re-introduce
overfitting, so the LLM shapes the in-sample tail while the agent is judged
out-of-sample.

The fed signal is endogenous to the agent (honest disclosure). The estimator is
fit on the returns generated by the SAC policy that was itself trained under the
candidate reward (call path: ``llm.loop`` trains the policy, then
``EnvBundle.train_returns(policy)`` rolls THAT policy and the estimator fits its
realized ``info["port_ret"]`` series). H2 is therefore a comparison of two coupled
reward -> policy -> measurement loops (scalar-fed vs tail-fed): the fed
distribution is shaped by the very agent it steers, which is the legitimate object
of study (does richer tail feedback steer a better reward-and-policy?), not an
exogenous risk measurement. The train/val split mitigates selection-overfitting
(fed in-sample, scored out-of-sample) but does NOT break this endogeneity — no
claim of an agent-independent / "works on any agent" tail measurement is made.

Estimator design (FINAL_PLAN F.2, B.4, audit B-1):
  - EMPIRICAL is PRIMARY for the body of the distribution (CVaR / quantiles /
    left-tail mass / robust skew) — for a 1-D sample the empirical quantile is the
    efficient estimator. Used for alpha in {25%, 10%}.
  - GENERALIZED-PARETO / EVT tail fit (per EX-DRL) for the extreme levels
    (CVaR-5%, CVaR-1%): the tail holds only ~7-37 observations, so an EVT fit makes
    those signals estimable rather than sample-noise. A neural quantile network is
    NOT used for the headline statistics.
  - left_tail_mass and robust_skew are derived from empirical quantiles (B.10).

Frozen tail-diagnostic set (returned by `tail_stats`, exactly these keys):
  cvar_01, cvar_05, cvar_10, cvar_25, left_tail_mass, robust_skew.
  cvar_01 is RETAINED BUT EXPLICITLY FLAGGED HIGH-VARIANCE (audit B-7); it is the
  EVT-estimated extreme and must be documented as such wherever it is reported.

EVT-tail CVaR derivation (peaks-over-threshold). Working on losses ``L = -returns``
with a high threshold ``u`` (the empirical loss-quantile at ``threshold_q``), the
exceedances ``Y = L - u | L > u`` follow a Generalized-Pareto law GPD(xi, beta).
With tail probability ``p`` (= ``alpha``) and tail-exceedance fraction
``F_u = P(L > u)`` the loss Value-at-Risk and Conditional VaR are::

    VaR_p  = u + (beta / xi) * ((p / F_u) ** (-xi) - 1)            (xi != 0)
    CVaR_p = (VaR_p + beta - xi * u) / (1 - xi)                    (xi < 1)

and the (signed) return-space CVaR reported to callers is ``-CVaR_p``. The closed
form is only used inside the **regular MLE region** ``-0.5 < xi < 1``: for ``xi >= 1``
the tail has infinite mean (CVaR undefined) and for ``xi <= -0.5`` the GPD MLE is
non-regular (Smith 1985, Biometrika 72(1): the likelihood loses its standard root-n /
asymptotic-normal behaviour), so OUTSIDE that open interval ``_evt_cvar`` falls back to
the empirical CVaR (see :data:`EVT_NONREGULAR_XI_NOTE`). On the small-sample shapes fitted here (the
downward-biased MLE sits inside the regular interval, not the true loss tail) both
guards fire essentially never; they are defensive.

GPD parameter estimation — PLAIN MAXIMUM LIKELIHOOD (no bias correction).
``(xi, beta)`` are fitted by **plain maximum likelihood** via
``scipy.stats.genpareto.fit`` (the McNeil-Frey-Embrechts 2005 §7.2.3 POT estimator;
``fit`` is unmodified MLE — it carries no small-sample bias correction). On few
exceedances the GPD MLE is known to be biased and high-variance (Giles; arXiv
2007.10780). The **bias-corrected / unbiased POT estimator (UPOT) of Troop, Godin &
Yu, 2021 (arXiv:2103.05059) is NOT implemented here — it is FUTURE WORK**, for the
following first-hand-measured reasons (do not over-read this estimator as bias-corrected):

  * Troop UPOT corrects two BIAS sources (GPD-approximation error, eq. 17-18, and
    MLE parameter bias, eq. 14) via second-order regular-variation machinery: a
    Fraga-Alves (2003) rho-hat (adaptive ADARHO selection) and a Hill-moment A-hat
    (eq. 22). That machinery requires a **heavy** tail (xi > 0; the Hill estimator
    underlying rho-hat / A-hat is only consistent for xi > 0) and is validated by the
    authors only at **n in [5e3, 5e4] and alpha in {0.998, 0.999}** with threshold
    percentiles 0.79-0.98 (their Tables 1-2).
  * This estimator's regime is the OPPOSITE corner: measured at n~750 training returns
    (the pre-Split-C fed window), alpha in {0.05, 0.01}, threshold_q=0.10 (~75
    exceedances). The EXECUTED Split-C fed window is the full train rollout ~2,961
    sessions => ~296 exceedances at threshold_q=0.10 and ~30 cvar_01 tail points —
    direction unchanged, the estimator strictly better-fed. Measured here (replayable):
    (a) the plain-MLE CVaR error at n=750 is ~98% VARIANCE, ~2-6% bias (CVaR-5% bias
    ~ -0.1%, CVaR-1% bias ~ +0.9% of the true value) — UPOT corrects bias, not
    variance, so it cannot help the dominant error term; and (b) on these portfolio
    losses the small-sample GPD MLE returns xi <= 0 in ~94% of n=750 draws (a downward-bias
    artefact at ~75 exceedances, NOT a genuinely light tail),
    where the rho-hat / A-hat correction is UNDEFINED (A-hat's denominator
    2*xi_MLE*rho_hat*M1 -> 0) and ill-conditioned (|A-hat| > 5 or NaN otherwise).
    A faithful UPOT would therefore NO-OP (fall back to MLE/empirical) in the vast
    majority of cases and inject instability in the rest — strictly worse RMSE here.
  * Accompanying stability exhibit: ``threshold_sensitivity`` reports the POT
    bias-variance spread of the fed CVaR levels across thresholds (the honest
    diagnostic shipped in lieu of the correction).

Audit refs: B-1 (empirical primary + EVT tails), B-2 (measure on training returns),
B-7 (CVaR-1% kept-but-flagged); see also DEEP_H2 sec. 6.2 / PREREGISTRATION sec. 4.
"""

from __future__ import annotations

import logging
import math

import numpy as np
from scipy import stats

_LOG = logging.getLogger(__name__)

#: CVaR-1% is the EVT-estimated extreme; it is retained but flagged high-variance
#: (audit B-7). Reported wherever cvar_01 appears.
CVAR_01_HIGH_VARIANCE_NOTE = (
    "cvar_01 is an EVT-extrapolated extreme estimated from few tail "
    "observations and is high-variance (audit B-7)."
)

#: Honest disclosure of the EVT estimator actually used (DEEP_H2 sec. 6.2). The EVT
#: tail CVaR is the PLAIN GPD maximum-likelihood POT estimator (scipy
#: ``genpareto.fit``, no bias correction); the bias-corrected/unbiased POT of Troop,
#: Godin & Yu (2021, arXiv:2103.05059) is FUTURE WORK — its second-order
#: regular-variation correction is built for heavy tails (xi > 0) at large samples and
#: is undefined/ill-conditioned in this estimator's regime (~750 returns, alpha<=0.05,
#: where the GPD MLE returns xi <= 0 for ~94% of realistic portfolio-loss samples).
#: See the module docstring for the first-hand measurements and the rationale.
EVT_ESTIMATOR_NOTE = (
    "EVT tail CVaR uses the plain GPD maximum-likelihood POT estimator (no "
    "bias correction); the Troop et al. (2021) bias-corrected POT is future work "
    "(undefined/ill-conditioned at this sample size and tail level)."
)

#: The EVT/GPD CVaR formula is only used inside the REGULAR MLE region of the shape
#: parameter, ``-0.5 < xi < 1``: for ``xi >= 1`` the tail has infinite mean (CVaR
#: undefined) and for ``xi <= -0.5`` the GPD MLE is non-regular (Smith 1985: the
#: likelihood loses its standard root-n / asymptotic-normal behaviour). Outside this
#: open interval ``_evt_cvar`` falls back to the empirical CVaR. On the actual
#: portfolio-loss tails the small-sample MLE shape sits in (-0.5, 0.3) (a downward-biased
#: ESTIMATE, not the true tail), so this guard fires essentially never; it is defensive.
EVT_NONREGULAR_XI_NOTE = (
    "EVT/GPD CVaR is used only for -0.5 < xi < 1 (the regular MLE region); for "
    "xi <= -0.5 (non-regular GPD MLE, Smith 1985) or xi >= 1 (infinite-mean tail) "
    "the estimator falls back to the empirical CVaR."
)

#: Levels STRICTLY ABOVE this fraction use the empirical estimator for CVaR; at or
#: below it, the EVT/GPD tail fit is used (so CVaR-5% is EVT) (audit B-1). Matches the
#: strict ``alpha <= EVT_ALPHA_CUTOFF`` routing in ``cvar()`` (audit fix: doc had the
#: boundary direction inverted vs the code).
EVT_ALPHA_CUTOFF = 0.05

#: Pre-registered multiplier for left_tail_mass = P(return < -k * std) (B.10).
LEFT_TAIL_K = 2.0

#: The FED HEADLINE tail levels — the CVaR levels that are (a) written into the
#: distributional arm's feedback block and (b) co-primary tail metrics (DEEP_H2 §4.3).
#: CVaR-5% routes through the EVT/GPD fit (alpha <= EVT_ALPHA_CUTOFF), and per ``_evt_cvar``
#: it can SILENTLY fall back to empirical if a candidate's tail is degenerate / out-of-region
#: (``exceed_frac`` is data-dependent — DEEP_H2 §6.3). To keep that switch auditable rather than
#: silent, every routed FED-level evaluation is recorded in :data:`_FED_ESTIMATOR_PATHS` and an
#: estimator change ACROSS candidates is logged (see ``ReturnDistribution._record_fed_estimator``).
FED_HEADLINE_CVAR_LEVELS: tuple[float, ...] = (0.05,)

#: Process-level registry of the estimator path ("evt" | "empirical") taken at each FED headline
#: level, in first-seen order, so a per-candidate EVT<->empirical switch in the FED CVaR-5% is
#: explicit + logged (T2.8b). Keyed by the rounded level. Reset via ``reset_fed_estimator_log``.
_FED_ESTIMATOR_PATHS: dict[float, list[str]] = {}


def reset_fed_estimator_log() -> None:
    """Clear the cross-candidate FED-estimator consistency registry (:data:`_FED_ESTIMATOR_PATHS`).

    Call at the start of a campaign/arm sweep so the "consistent estimator across candidates"
    check (T2.8b / DEEP_H2 §6.3) spans exactly the intended set of candidates. Safe to call any time.
    """
    _FED_ESTIMATOR_PATHS.clear()


def fed_estimator_log() -> dict[float, list[str]]:
    """Return a copy of the FED-estimator path registry (per FED headline level, first-seen order).

    A level whose list contains MORE THAN ONE distinct estimator ("evt" and "empirical") flagged a
    silent per-candidate switch in the fed CVaR-5% — the auditable record behind the logged warning.
    """
    return {k: list(v) for k, v in _FED_ESTIMATOR_PATHS.items()}


class ReturnDistribution:
    """Empirical-body + EVT-tail estimator over realized training returns.

    Fit once on the training-period realized portfolio simple (arithmetic) returns,
    then query quantiles, CVaR at a level, or the full frozen tail-diagnostic set.
    See the module docstring and FINAL_PLAN F.2 for the algorithm and audit
    references.

    Attributes
    ----------
    sorted_returns : np.ndarray
        The training returns sorted ascending.
    T : int
        Number of training observations.
    threshold_q : float
        Lower-tail probability defining the EVT threshold (default 0.10).
    xi, beta, u, exceed_frac : float
        Fitted GPD shape and scale, the loss threshold, and the fraction of losses
        exceeding it.
    """

    def __init__(self, threshold_q: float = 0.10) -> None:
        self.threshold_q = float(threshold_q)
        #: When True, cvar('auto') skips the cross-candidate FED-estimator audit — set on the internal
        #: bootstrap-replicate refits (``_bootstrap_cvars``) so they don't pollute the registry or storm
        #: the warning log (2026-07-05). Default False = a genuine fed-candidate measurement records.
        self._suppress_fed_estimator_record = False
        self.sorted_returns: np.ndarray | None = None
        #: The finite returns in TIME order (NOT sorted). The stationary block bootstrap (``cvar_ci`` /
        #: ``cvar_bias``) must resample in serial order to preserve dependence, so we keep the un-sorted array
        #: in addition to ``sorted_returns`` (which the empirical/EVT point estimators use). Additive; the
        #: existing fitted attributes + ``tail_stats`` values are unchanged.
        self._raw: np.ndarray | None = None
        self.T: int = 0
        self.xi: float = float("nan")
        self.beta: float = float("nan")
        self.u: float = float("nan")
        self.exceed_frac: float = float("nan")

    def fit(self, train_realized_returns: np.ndarray) -> "ReturnDistribution":
        """Sort the training returns and fit the EVT lower-tail model.

        Parameters
        ----------
        train_realized_returns : np.ndarray
            1-D array of training-period realized portfolio **simple** (arithmetic,
            per-step ``gross - cost``) returns from the trained policy's own rollout
            (anonymized; no tickers/dates). These are endogenous to the candidate
            reward that trained the policy — see the module docstring.

        Returns
        -------
        ReturnDistribution
            ``self``, fitted.

        Raises
        ------
        ValueError
            If the input is empty or not 1-D after flattening.
        """
        arr = np.asarray(train_realized_returns, dtype=float).ravel()
        arr = arr[np.isfinite(arr)]
        if arr.size == 0:
            raise ValueError("train_realized_returns must be non-empty and finite")

        self.sorted_returns = np.sort(arr)
        self._raw = arr  # time-ordered finite returns (block bootstrap needs serial order, not sorted)
        self.T = int(arr.size)

        # Peaks-over-threshold on losses L = -returns.
        losses = -arr
        self.u = float(np.quantile(losses, 1.0 - self.threshold_q))
        exceedances = losses[losses > self.u] - self.u
        self.exceed_frac = float(exceedances.size) / float(self.T)

        if exceedances.size >= 2:
            # Fit GPD with location fixed at 0 (exceedances are >= 0 by construction).
            # PLAIN maximum likelihood (scipy genpareto.fit is unmodified MLE; it
            # carries NO small-sample bias correction). The Troop et al. (2021)
            # bias-corrected POT is future work — see the module docstring and
            # EVT_ESTIMATOR_NOTE for why it is undefined/ill-conditioned here.
            try:
                xi, _loc, beta = stats.genpareto.fit(exceedances, floc=0.0)
            except Exception:  # P20/P19: a rare optimizer failure on a pathological tail must NOT
                xi, beta = float("nan"), float("nan")  # crash a campaign candidate — degrade to exp-tail below.
            # P20/P19 (fed-path robustness, mirroring the diagnostic path in ood_stress.py): a NON-finite
            # xi/beta would otherwise bypass the downstream ``abs(xi) >= 1e-8`` degenerate guard (since
            # ``abs(nan) >= 1e-8`` is False) and yield a NaN fed CVaR on the science-bearing feed. Fall back
            # to the same exponential-tail (xi -> 0) the <2-exceedance branch uses.
            if np.isfinite(xi) and np.isfinite(beta):
                self.xi = float(xi)
                self.beta = float(beta)
            else:
                self.xi = 0.0
                self.beta = float(exceedances.mean())
        else:
            # Too few exceedances to fit; fall back to exponential-tail (xi -> 0).
            self.xi = 0.0
            self.beta = float(exceedances.mean()) if exceedances.size else float("nan")

        return self

    def _check_fitted(self) -> np.ndarray:
        if self.sorted_returns is None:
            raise RuntimeError("ReturnDistribution.fit must be called before querying")
        return self.sorted_returns

    def quantiles(self, taus: list[float]) -> dict[float, float]:
        """Return empirical quantiles of the fitted return sample.

        Parameters
        ----------
        taus : list of float
            Quantile levels in (0, 1), e.g. [0.05, 0.10, 0.25, 0.50, 0.95].

        Returns
        -------
        dict
            Mapping from each tau to its empirical quantile.
        """
        arr = self._check_fitted()
        return {float(t): float(np.quantile(arr, t)) for t in taus}

    def _empirical_cvar(self, alpha: float) -> float:
        """Empirical CVaR: mean of the worst ceil(alpha*T) returns (signed)."""
        arr = self._check_fitted()
        n = max(1, math.ceil(alpha * self.T))
        worst = arr[:n]
        return float(worst.mean())

    def _evt_cvar(self, alpha: float) -> float:
        """EVT/GPD-based CVaR at level alpha (signed return-space).

        Uses the fitted (xi, beta, u, exceed_frac) per the peaks-over-threshold
        formulas in the module docstring, with GPD parameters from **plain maximum
        likelihood** (``scipy.stats.genpareto.fit``; no bias correction — the Troop
        et al. 2021 bias-corrected POT is future work, see :data:`EVT_ESTIMATOR_NOTE`
        and the module docstring). Falls back to empirical if the level is not in the
        fitted tail, or the fit is degenerate, or the fitted shape leaves the regular
        MLE region ``-0.5 < xi < 1`` (xi >= 1 infinite-mean / xi <= -0.5 non-regular
        GPD MLE, Smith 1985 — :data:`EVT_NONREGULAR_XI_NOTE`).
        """
        if self._evt_falls_back(alpha) is not None:
            # Out of the fitted tail / degenerate fit / non-regular shape -> empirical.
            return self._empirical_cvar(alpha)
        xi, beta, u, fu = self.xi, self.beta, self.u, self.exceed_frac
        if abs(xi) < 1e-8:
            # xi -> 0: exponential tail.
            var_loss = u + beta * math.log(fu / alpha)
            cvar_loss = var_loss + beta
        else:
            var_loss = u + (beta / xi) * ((alpha / fu) ** (-xi) - 1.0)
            cvar_loss = (var_loss + beta - xi * u) / (1.0 - xi)
        return -float(cvar_loss)

    def _evt_falls_back(self, alpha: float) -> str | None:
        """Reason the EVT/GPD branch would FALL BACK to empirical at ``alpha``, else ``None``.

        Single source of truth for the EVT-vs-empirical switch (used by both ``_evt_cvar`` and the
        FED-estimator consistency log, T2.8b). Returns a short reason string when the EVT closed form
        is NOT used — so the routed estimator is ``"empirical"`` — or ``None`` when EVT IS used:

          * ``"degenerate_fit"`` — non-finite beta/u, or no exceedances (``exceed_frac <= 0``);
          * ``"alpha_gt_exceed_frac"`` — the level is shallower than the tail mass (``alpha > F_u``),
            the DATA-DEPENDENT switch DEEP_H2 §6.3 flags (``exceed_frac`` varies per candidate);
          * ``"xi_ge_1"`` — infinite-mean tail (CVaR undefined);
          * ``"xi_le_-0.5"`` — non-regular GPD MLE region (Smith 1985 — :data:`EVT_NONREGULAR_XI_NOTE`).
        """
        xi, beta, u, fu = self.xi, self.beta, self.u, self.exceed_frac
        if not (np.isfinite(beta) and np.isfinite(u) and fu > 0.0):
            return "degenerate_fit"
        if alpha > fu:  # POT approximation valid only for alpha within the tail mass
            return "alpha_gt_exceed_frac"
        if abs(xi) >= 1e-8:
            if xi >= 1.0:
                return "xi_ge_1"
            if xi <= -0.5:
                return "xi_le_-0.5"
        return None

    def _record_fed_estimator(self, alpha: float) -> None:
        """Record + log the estimator path for a FED HEADLINE level so a per-candidate switch is auditable.

        Appends ``"evt"``/``"empirical"`` (per :meth:`_evt_falls_back`) to the process-level registry
        :data:`_FED_ESTIMATOR_PATHS` for ``alpha``, and emits a ``WARNING`` the first time a level's path
        DIFFERS from the estimator it used on the first candidate. This makes the silent EVT<->empirical
        switch in the fed CVaR-5% (DEEP_H2 §6.3, T2.8b) EXPLICIT and logged — it does NOT change the
        returned value (no science change). Inspect via :func:`fed_estimator_log`; scope with
        :func:`reset_fed_estimator_log`.
        """
        key = round(float(alpha), 10)
        reason = self._evt_falls_back(alpha)
        path = "empirical" if reason is not None else "evt"
        seen = _FED_ESTIMATOR_PATHS.setdefault(key, [])
        if seen and path != seen[0]:
            _LOG.warning(
                "FED CVaR-%.0f%% estimator INCONSISTENT across candidates: first used %r, "
                "this candidate used %r (reason=%s). The fed headline tail level switched "
                "EVT<->empirical between candidates (exceed_frac is data-dependent; DEEP_H2 "
                "6.3 / T2.8b). The contrast may mix estimators across arms — audit before "
                "reporting the tail leg.",
                100.0 * alpha,
                seen[0],
                path,
                reason,
            )
        seen.append(path)

    def cvar(self, alpha: float, *, method: str = "auto") -> float:
        """Conditional Value-at-Risk at level alpha (mean of the worst alpha tail).

        For ``alpha`` > :data:`EVT_ALPHA_CUTOFF` the empirical estimator is used; for
        ``alpha`` <= :data:`EVT_ALPHA_CUTOFF` (i.e. CVaR-5% and CVaR-1%) the EVT/GPD
        tail fit is used (audit B-1). The EVT fit is the **plain GPD maximum-likelihood
        POT** estimator (no bias correction; the Troop et al. 2021 bias-corrected POT
        is future work — :data:`EVT_ESTIMATOR_NOTE`). cvar_01 is therefore EVT-estimated
        and high-variance (audit B-7, :data:`CVAR_01_HIGH_VARIANCE_NOTE`). (Audit fix:
        the boundary direction here previously contradicted the ``alpha <= ...`` code.)

        Parameters
        ----------
        alpha : float
            Tail probability level, e.g. 0.01, 0.05, 0.10, 0.25.
        method : {"auto", "empirical", "evt"}, optional
            Force an estimator for cross-checking EVT against empirical. ``"auto"``
            (default) routes by ``alpha`` as described above.

        Returns
        -------
        float
            The (signed) CVaR at level alpha (negative for a loss tail). Monotone
            non-increasing as ``alpha`` shrinks.
        """
        self._check_fitted()
        if not 0.0 < alpha < 1.0:
            raise ValueError("alpha must be in (0, 1)")
        if method == "empirical":
            return self._empirical_cvar(alpha)
        if method == "evt":
            return self._evt_cvar(alpha)
        if method != "auto":
            raise ValueError(f"unknown method: {method!r}")
        # T2.8b: for a FED HEADLINE level (CVaR-5%), record which estimator the routing actually
        # used and log if it differs across candidates — the data-dependent EVT<->empirical switch
        # (DEEP_H2 §6.3) is then explicit, not silent. Only in "auto" (the fed path); the value is
        # unchanged. Match on the rounded level so 0.05 vs 0.0500000001 still registers.
        if not self._suppress_fed_estimator_record and any(
            abs(alpha - lvl) < 1e-12 for lvl in FED_HEADLINE_CVAR_LEVELS
        ):
            self._record_fed_estimator(alpha)
        if alpha <= EVT_ALPHA_CUTOFF:
            return self._evt_cvar(alpha)
        return self._empirical_cvar(alpha)

    def tail_stats(self) -> dict:
        """Return the frozen tail-diagnostic set fed to the distributional arm.

        Returns EXACTLY the keys:
            cvar_01, cvar_05, cvar_10, cvar_25, left_tail_mass, robust_skew.

        cvar_01 is the EVT-estimated extreme and is documented high-variance
        (B-7, :data:`CVAR_01_HIGH_VARIANCE_NOTE`). left_tail_mass and robust_skew
        are derived from empirical quantiles (B.10):

            left_tail_mass = mean(returns < -k * std), k = 2.0
            robust_skew    = ((Q95 - Q50) - (Q50 - Q05)) / (Q95 - Q05 + eps)

        This is the **Groeneveld-Meeden (1984) generalized quantile skewness**
        gamma(p) at p = 0.05, written so that it is NEGATIVE when the left tail
        is longer, per the frozen design's stated sign convention. Equivalently
        ``-((Q50-Q05)-(Q95-Q50))/(Q95-Q05+eps)``.

        NAME CORRECTED 2026-07-26 (dispatch T2): this previously read "the
        (quantile-based) **Bowley** skewness". Bowley's coefficient is the
        QUARTILE case, gamma(0.25) = ((Q75-Q50)-(Q50-Q25))/(Q75-Q25); the
        statistic implemented here uses the 5th/95th percentiles, i.e. gamma(0.05)
        of the same Groeneveld-Meeden family. The FROZEN key, formula and value
        are UNCHANGED - this is documentation accuracy only, so that a reader
        checking the reference finds the estimator we actually compute.

        Returns
        -------
        dict
            Dict with exactly the six frozen fields above.
        """
        arr = self._check_fitted()
        q = self.quantiles([0.05, 0.50, 0.95])
        q05, q50, q95 = q[0.05], q[0.50], q[0.95]
        eps = 1e-12
        std = float(arr.std())
        left_tail_mass = float(np.mean(arr < -LEFT_TAIL_K * std))
        robust_skew = ((q95 - q50) - (q50 - q05)) / ((q95 - q05) + eps)
        return {
            "cvar_01": self.cvar(0.01),
            "cvar_05": self.cvar(0.05),
            "cvar_10": self.cvar(0.10),
            "cvar_25": self.cvar(0.25),
            "left_tail_mass": left_tail_mass,
            "robust_skew": float(robust_skew),
        }

    def exceedance_count(self, alpha: float) -> int:
        """Effective tail sample size behind CVaR-``alpha`` = ``ceil(alpha*T)`` (the worst-``alpha`` block).

        At the executed Split-C fed window (``T~2,961``, the full train rollout) this is ~149
        (alpha=0.05) / ~30 (alpha=0.01) — the deep tail still BELOW the ~50-100-exceedance reliability
        standard (the pre-Split-C ``T~750`` window gave ~37 / ~7), so the deep-tail CVaR remains
        high-variance (Belzile & Davison 2022). Surfaced via
        :meth:`reliability` and the uncertainty report so a consumer can weight the estimate by its evidence.
        """
        self._check_fitted()
        return int(max(1, math.ceil(float(alpha) * self.T)))

    def reliability(self, alpha: float) -> str:
        """Reliability tier for CVaR-``alpha`` from its tail sample size (Belzile-Davison 2022 small-sample
        standard): ``"high"`` (>30 exceedances), ``"medium"`` (7-30), ``"low"`` (<7). Reported/feedable as
        METADATA so a downstream consumer weights the estimate by evidence (not a value change)."""
        n_exc = self.exceedance_count(alpha)
        if n_exc > 30:
            return "high"
        if n_exc >= 7:
            return "medium"
        return "low"

    @staticmethod
    def _stationary_block_indices(t: int, expected_block: float, rng: np.random.Generator) -> np.ndarray:
        """Stationary (Politis-Romano 1994) block-bootstrap indices for a length-``t`` series.

        Geometric block lengths with mean ``expected_block`` (restart prob ``p = 1/expected_block``), wrapped
        circularly so every index is in ``[0, t)``. Kept LOCAL (no cross-layer import of
        ``src.inference.bootstrap``) so ``measurement.py`` stays self-contained; behaviourally the same
        stationary scheme. DETERMINISTIC given ``rng`` (numpy ``default_rng``/PCG64 — platform-independent).
        """
        p = 1.0 / max(1.0, float(expected_block))
        idx = np.empty(t, dtype=np.int64)
        cur = int(rng.integers(0, t))
        for i in range(t):
            idx[i] = cur
            cur = int(rng.integers(0, t)) if rng.random() < p else (cur + 1) % t
        return idx

    def _bootstrap_cvars(
        self, alpha: float, n_boot: int, expected_block: float | None, seed: int
    ) -> np.ndarray:
        """Refit the empirical+EVT estimator on ``n_boot`` STATIONARY-BLOCK resamples of the TIME-ORDERED
        returns and return the CVaR-``alpha`` of each. Block bootstrap (not IID) preserves serial dependence —
        the correct scheme for returns. Side-effect-free (fresh fits); DETERMINISTIC given ``seed``."""
        if self._raw is None:
            raise RuntimeError("ReturnDistribution.fit must be called before bootstrap uncertainty queries")
        raw = self._raw
        t = int(raw.size)
        eb = float(expected_block) if expected_block else max(2.0, round(t ** (1.0 / 3.0)))
        rng = np.random.default_rng(int(seed))
        out = np.empty(int(n_boot), dtype=float)
        for b in range(int(n_boot)):
            idx = self._stationary_block_indices(t, eb, rng)
            replicate = ReturnDistribution(threshold_q=self.threshold_q)
            # 2026-07-05: mark these internal REFITS so their per-replicate cvar('auto') calls do NOT
            # register in the cross-candidate FED-estimator audit — otherwise cvar_ci/cvar_bias/
            # cvar_uncertainty_report polluted _FED_ESTIMATOR_PATHS with up to n_boot entries and
            # emitted a WARNING STORM ("FED CVaR estimator INCONSISTENT across candidates") whenever a
            # resample flipped EVT<->empirical. The reported CI/bias values are byte-identical.
            replicate._suppress_fed_estimator_record = True
            out[b] = replicate.fit(raw[idx]).cvar(alpha)
        return out

    def cvar_ci(
        self,
        alpha: float,
        *,
        n_boot: int = 1000,
        expected_block: float | None = None,
        ci: float = 0.90,
        seed: int = 0,
    ) -> tuple[float, float]:
        """Percentile confidence interval for CVaR-``alpha`` via the STATIONARY BLOCK bootstrap.

        Propagates threshold + parameter uncertainty into the reported tail measure (Scarrott & MacDonald
        2012 best practice; an IID bootstrap is wrong for serially-dependent returns — Politis-Romano). Refits
        the empirical+EVT estimator on each resample; returns the ``(lo, hi)`` percentile interval at coverage
        ``ci``. ``expected_block`` defaults to ``~T**(1/3)`` (standard dependent-bootstrap rule). DETERMINISTIC
        given ``seed``; does not mutate ``self`` and does not change ``tail_stats``/``cvar`` values.
        """
        boots = self._bootstrap_cvars(alpha, n_boot, expected_block, seed)
        lo_q = (1.0 - float(ci)) / 2.0
        lo, hi = np.quantile(boots, [lo_q, 1.0 - lo_q])
        return float(lo), float(hi)

    def cvar_bias(
        self,
        alpha: float,
        *,
        n_boot: int = 500,
        expected_block: float | None = None,
        seed: int = 0,
    ) -> float:
        """Block-bootstrap estimate of the small-sample BIAS of CVaR-``alpha`` (mean bootstrap CVaR − point).

        Reported as a bias SENSITIVITY beside the point estimate. The verified verdict (deep-research
        2026-06-28, matching the prior 0-3 refutation) is that analytic (Giles et al.) and bootstrap
        bias-correction are COMPARABLE at this sample size — neither is claimed superior — so we report the
        bootstrap bias rather than asserting a correction. The full Troop et al. (2021) UPOT bias-correction
        stays FUTURE WORK: its second-order regular-variation machinery is undefined/ill-conditioned in this
        regime (xi<=0 for the bulk of realistic portfolio-loss samples) — see the module docstring /
        :data:`EVT_ESTIMATOR_NOTE`. DETERMINISTIC given ``seed``.
        """
        boots = self._bootstrap_cvars(alpha, n_boot, expected_block, seed)
        return float(np.mean(boots) - self.cvar(alpha))

    def cvar_uncertainty_report(
        self,
        levels: tuple[float, ...] = FED_HEADLINE_CVAR_LEVELS,
        *,
        n_boot: int = 1000,
        seed: int = 0,
    ) -> dict[str, dict[str, float | str]]:
        """Analysis-facing uncertainty artifact for the fed CVaR level(s): per level, the point estimate, the
        block-bootstrap 90% CI, the bootstrap bias estimate, the effective exceedance count, and the
        reliability tier. This is the *reported* uncertainty propagation (the fed feedback block itself is
        unchanged — enriching it with the CI is a flagged, arms-parity-gated option, not the default).
        DETERMINISTIC given ``seed``."""
        self._check_fitted()
        report: dict[str, dict[str, float | str]] = {}
        for lvl in levels:
            lo, hi = self.cvar_ci(lvl, n_boot=n_boot, seed=seed)
            report[f"cvar_{int(round(lvl * 100)):02d}"] = {
                "point": self.cvar(lvl),
                "ci_lo": lo,
                "ci_hi": hi,
                "bias": self.cvar_bias(lvl, n_boot=max(200, n_boot // 2), seed=seed),
                "n_exceedances": float(self.exceedance_count(lvl)),
                "reliability": self.reliability(lvl),
            }
        return report

    def threshold_sensitivity(
        self,
        alpha: float = 0.01,
        threshold_qs: tuple[float, ...] = (0.05, 0.10, 0.15, 0.20),
    ) -> dict[str, float]:
        """Diagnostic for the POT bias-variance trade-off (deep-research #2, audit B-7).

        Re-estimates the EVT CVaR at level ``alpha`` across several peaks-over-threshold
        choices and reports the spread. The extreme-tail CVaR (esp. CVaR-1%: ~30 tail
        points on the executed Split-C fed window of ~2,961 train-rollout sessions; ~7-8
        on the pre-Split-C ~750) is sensitive to the threshold; a large spread flags an
        unstable estimate to treat with caution. Side-effect-free (uses fresh fits, does
        not mutate ``self``).

        NOTE: the EVT CVaR re-estimated here is the **plain GPD maximum-likelihood POT**
        estimator (no bias correction). A *bias-corrected* POT estimator (Troop et al.
        2021, arXiv:2103.05059) is **future work, NOT implemented** — its second-order
        regular-variation correction is built for heavy tails (xi > 0) at large samples
        and is undefined/ill-conditioned in this regime (measured at the pre-Split-C
        n~750; the executed ~2,961-session Split-C fed window is strictly better-fed,
        direction unchanged — see :data:`EVT_ESTIMATOR_NOTE` and the module docstring). This method is the
        honest stability diagnostic shipped in its place: report the cross-threshold
        spread as the bounding exhibit for the fed CVaR levels.

        Parameters
        ----------
        alpha : float
            Tail level to probe (default 0.01).
        threshold_qs : tuple of float
            Lower-tail threshold probabilities to refit at.

        Returns
        -------
        dict
            ``{"<q>": cvar, ..., "spread": max-min, "cv": spread/|mean|, "n_empirical_fallback": count}``.
            ``n_empirical_fallback`` counts the probed thresholds whose EVT CVaR routed to the empirical
            fallback (``_evt_falls_back``); if > 0 the spread mixes GPD and empirical estimates and bounds
            instability only loosely.
        """
        self._check_fitted()  # fitted-state guard (raises before any refit)
        # Refit on the TIME-ORDERED returns, NOT ``sorted_returns`` (2026-07-26 review). Every value
        # this method returns is byte-identical either way — the POT/GPD path (threshold quantile,
        # exceedance set, MLE fit) is order-invariant, verified. The reason to pass ``_raw`` is that
        # each replicate below is a fully-formed ReturnDistribution, and one built from a SORTED
        # series carries a SORTED ``_raw`` — the very array the stationary block bootstrap resamples.
        # A later ``rd_q.cvar_ci()`` / ``cvar_bias()`` would then resample monotone runs, destroying
        # the serial dependence the block scheme exists to preserve, and silently report a ~3.5x
        # too-wide interval. Keep every ReturnDistribution consistent with its documented invariant.
        arr = self._raw
        per_threshold: dict[str, float] = {}
        vals: list[float] = []
        n_empirical_fallback = 0
        for q in threshold_qs:
            rd_q = ReturnDistribution(threshold_q=q).fit(arr)
            cv = rd_q._evt_cvar(alpha)
            per_threshold[f"{q:.2f}"] = cv
            vals.append(cv)
            if rd_q._evt_falls_back(alpha) is not None:
                n_empirical_fallback += 1
        v = np.asarray(vals, dtype=float)
        spread = float(np.nanmax(v) - np.nanmin(v))
        mean = float(np.nanmean(v))
        per_threshold["spread"] = spread
        per_threshold["cv"] = float(spread / (abs(mean) + 1e-12))
        # How many of the probed thresholds routed to the EMPIRICAL fallback (not the GPD closed form,
        # per ``_evt_falls_back``): a nonzero count means the cross-threshold spread mixes two estimators,
        # so read it as a loose upper bound on EVT instability, not a like-for-like GPD sensitivity.
        per_threshold["n_empirical_fallback"] = float(n_empirical_fallback)
        return per_threshold
