#!/usr/bin/env python3
"""Build the dissertation PDF from the paper/ markdown chapters (the DELIVERABLE pipeline).

Why this exists
---------------
The dissertation is graded on the submitted PDF alone, but until 2026-07-02 the repo had NO
md->PDF toolchain at all (audit NEW-LENS A: no pandoc/LaTeX anywhere, no build target) — the
final deliverable was un-producible. This script + the PINNED portable toolchain in ``tools/``
(pandoc 3.10 + Tectonic 0.16.9, downloaded 2026-07-02; no system install, reproducible) close
that gap and make the PDF compilable from day one, so compile problems surface MONTHS before
the 1-Sep deadline instead of at submission week.

What it does
------------
1. Assembles the chapters in the UCL-required section order (``ASSEMBLY`` below; internal
   working files like 00_FRAMING / 01_LITERATURE_DOSSIER are deliberately excluded).
2. Rewrites the repo's citation convention -- [`key`] / [`k1`; `k2`] -- into pandoc citeproc
   syntax ([@key] / [@k1; @k2]), OUTSIDE fenced code blocks only (code stays byte-intact).
3. Runs pandoc --citeproc with the Harvard "Cite Them Right" CSL (paper/harvard-cite-them-right.csl,
   the UCL-house Harvard variant) over paper/refs.bib, PDF via the Tectonic XeTeX engine
   (full unicode; downloads TeX packages on first run, then cached).
4. Surfaces every ``[WARNING]`` pandoc emits (esp. citeproc "reference not found" — a dangling
   key in the PDF is a grading defect) and exits non-zero on any ERROR.

Usage
-----
    python scripts/build_paper.py                  # -> paper/_build/dissertation.pdf
    python scripts/build_paper.py --md-only        # -> paper/_build/dissertation.md (inspect/word-count)
    python scripts/build_paper.py --out X.pdf      # custom output

The assembled intermediate markdown is ALWAYS written next to the PDF so the exact compiled
text is inspectable (and is what scripts/word_budget.py counts).

Notes / deliberate choices
--------------------------
* ``--toc`` generates the Table of Contents with REAL page numbers; FRONT_MATTER.md's manual
  ToC/LoF/LoT lists remain for the md readers — at final-compile time keep exactly one of the
  two (tracked in the ULTRAPLAN write-up punchlist, not silently resolved here).
* Figures are not yet embedded in the chapters (they land at write-time from
  paper/FIGURE_TABLE_MANIFEST.md); ``--resource-path`` already covers paper/ and outputs/figures
  so embeds compile the moment they appear.
* The toolchain paths are PINNED to the portable copies in tools/ and fail LOUD with install
  instructions if absent — no silent PATH fallback (a different pandoc version could render
  differently at submission time).
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

#: The UCL 16-section submission order (IFTE0008), mapped onto the chapter files. Internal
#: working documents (00_FRAMING, 01_LITERATURE_DOSSIER, FIGURE_TABLE_MANIFEST, NOMENCLATURE)
#: are NOT part of the deliverable and are deliberately absent.
ASSEMBLY: tuple[str, ...] = (
    "FRONT_MATTER.md",                          # cover/title/abstract/ack/ToC-lists/ethics/AI-disclosure
    "CH1_introduction.md",                      # Introduction
    "CH2_related_work.md",                      # Literature Review
    "02_CHAPTER_theory.md",                     # Theory (CH3)
    "CH4_methods.md",                           # Data + Methodology
    "CH5_prototype.md",                         # Prototype (machinery validation)
    "CH6_results.md",                           # Results
    "CH7_discussion_limitations_conclusion.md",  # Discussion, Limitations, Conclusions
    # References are GENERATED by citeproc AFTER this list; APPENDICES then append after References.
)

#: Appendices append AFTER the generated References div, because UCL requires the reference list to
#: PRECEDE the appendices. The Limitations Register was extracted out of CH7 -- where it printed
#: BEFORE the References div and so violated that order (audit P28) -- into its own file listed here.
#: Each appendix file is word-excluded: it is deliberately ABSENT from scripts/word_budget.py
#: BODY_CHAPTERS so it never counts toward the 10,000-word main-body limit. citeproc still collects
#: any citations occurring in the appendices below and renders them into the References div above, so
#: their cites resolve normally.
APPENDICES: tuple[str, ...] = (
    "APPENDIX_B_limitations.md",                 # Appendix B -- Limitations Register (was embedded in CH7)
)

PANDOC = REPO / "tools" / "pandoc-3.10" / "pandoc.exe"
TECTONIC = REPO / "tools" / "tectonic" / "tectonic.exe"
CSL = REPO / "paper" / "harvard-cite-them-right.csl"
BIB = REPO / "paper" / "refs.bib"

#: A bib key: starts with a letter and CONTAINS A 4-DIGIT YEAR (every key in refs.bib does) —
#: the year requirement is the discriminator that keeps bracketed inline code (e.g. [`np.mean`],
#: [`--gpu 3`]) out of the citation transform.
_KEY_RE = re.compile(r"`([A-Za-z][A-Za-z0-9_.+-]*\d{4}[A-Za-z0-9_:.+-]*)`")
#: A citation GROUP: a bracket (no nested brackets) containing >= 1 backticked year-key anywhere.
#: DOTALL-free but [^\[\]] admits newlines, so groups that WRAP ACROSS LINES are matched (the
#: first-compile audit found 18 such misses: multi-line groups + locator/prefix forms like
#: [`haarnoja2018sac`, SS5] and [`chow2015risk`, Prop. 1; cf. robust MDPs `iyengar2005robust`]).
_GROUP_RE = re.compile(
    r"\[([^\[\]]*?`[A-Za-z][A-Za-z0-9_.+-]*\d{4}[A-Za-z0-9_:.+-]*`[^\[\]]*?)\]"
)
_FENCE_RE = re.compile(r"^(```|~~~)")


def _transform_group(m: re.Match[str]) -> str:
    """Inside one citation group, turn every backticked year-key into @key; keep all other text.

    [`k2021a`]                              -> [@k2021a]
    [`k2021a`; `k2022b`]                    -> [@k2021a; @k2022b]     (incl. across a line wrap)
    [`k2018a`, SS5]                          -> [@k2018a, SS5]          (pandoc locator suffix)
    [`k2015a`, Prop. 1; cf. X `k2005b`]     -> [@k2015a, Prop. 1; cf. X @k2005b]  (prefix text)
    """
    return "[" + _KEY_RE.sub(lambda k: "@" + k.group(1), m.group(1)) + "]"


def rewrite_citations(md: str) -> str:
    """Rewrite the repo citation convention into pandoc citeproc syntax, skipping fenced code.

    Operates on whole unfenced SEGMENTS (not lines) so citation groups wrapping across newlines
    transform correctly; fenced code blocks (``` / ~~~) pass through byte-intact. Any transformed
    key that is absent from refs.bib then surfaces as a citeproc WARNING at compile time — the
    fail-loud path for dangling citations.
    """
    segments: list[str] = []
    buf: list[str] = []
    in_fence = False
    for line in md.splitlines(keepends=True):
        if _FENCE_RE.match(line.lstrip()):
            # flush the current segment, transform it iff it was prose
            segments.append("".join(buf) if in_fence else _GROUP_RE.sub(_transform_group, "".join(buf)))
            buf = [line]
            in_fence = not in_fence
            # the fence line itself belongs to the (new) code segment when opening, and to the
            # closing code segment when closing — either way it must not be transformed:
            segments.append("".join(buf))
            buf = []
            continue
        buf.append(line)
    segments.append("".join(buf) if in_fence else _GROUP_RE.sub(_transform_group, "".join(buf)))
    return "".join(segments)


def assemble(chapter_dir: Path, names: tuple[str, ...] = ASSEMBLY,
             appendices: tuple[str, ...] = APPENDICES) -> str:
    """Concatenate the deliverable in UCL submission order; fail loud on a missing file.

    Order: body chapters -> generated References div -> appendices. UCL requires the reference list
    to PRECEDE the appendices, so the appendices are appended AFTER the `#refs` div (citeproc still
    resolves any citations occurring inside them into that bibliography).
    """
    parts: list[str] = []
    missing = [n for n in (*names, *appendices) if not (chapter_dir / n).is_file()]
    if missing:
        raise FileNotFoundError(f"paper/ is missing required chapter file(s): {missing}")
    for name in names:
        text = (chapter_dir / name).read_text(encoding="utf-8")
        parts.append(text.rstrip() + "\n")
    # UCL requires an explicit References section; citeproc places the bibliography inside the
    # `#refs` div (otherwise it is appended headingless at the document end). Unnumbered per style.
    parts.append(
        "# References {.unnumbered}\n\n::: {#refs}\n:::\n"
    )
    # Appendices follow the References (UCL order: reference list before appendices).
    for name in appendices:
        text = (chapter_dir / name).read_text(encoding="utf-8")
        parts.append(text.rstrip() + "\n")
    # \newpage between chapters so each starts on a fresh page (pandoc passes raw LaTeX through).
    return "\n\\newpage\n\n".join(parts) + "\n"


def build(md_only: bool, out: Path | None) -> int:
    build_dir = REPO / "paper" / "_build"
    build_dir.mkdir(parents=True, exist_ok=True)
    assembled = rewrite_citations(assemble(REPO / "paper"))
    md_path = build_dir / "dissertation.md"
    md_path.write_text(assembled, encoding="utf-8")
    print(f"[build_paper] assembled {len(ASSEMBLY)} chapters + {len(APPENDICES)} appendix(es) -> {md_path}")

    if md_only:
        return 0

    for tool, hint in (
        (PANDOC, "download pandoc-3.10-windows-x86_64.zip from github.com/jgm/pandoc/releases "
                 "and extract into tools/ (see docs/CAMPAIGN_RUNBOOK.md, paper-build section)"),
        (TECTONIC, "download tectonic x86_64-pc-windows-msvc.zip from "
                   "github.com/tectonic-typesetting/tectonic/releases and extract into tools/tectonic/"),
        (CSL, "download harvard-cite-them-right.csl from the CSL styles repository into paper/"),
        (BIB, "paper/refs.bib is missing — the bibliography is required"),
    ):
        if not tool.exists():
            print(f"[build_paper] MISSING: {tool}\n  fix: {hint}", file=sys.stderr)
            return 2

    pdf_path = out or (build_dir / "dissertation.pdf")
    cmd = [
        str(PANDOC),
        str(md_path),
        "--from", "markdown+tex_math_dollars+raw_tex",
        "--citeproc",
        "--csl", str(CSL),
        "--bibliography", str(BIB),
        "--toc", "--toc-depth", "2",
        "--number-sections",
        "--pdf-engine", str(TECTONIC),
        "--resource-path", f"{REPO / 'paper'};{REPO / 'outputs' / 'figures'};{REPO}",
        "-V", "documentclass=report",
        "-V", "fontsize=12pt",
        "-V", "geometry:margin=2.5cm",
        # UCL IFTE0008 presentation rules: main text at 1.5 line spacing (setspace via pandoc's
        # linestretch) and a Helvetica-family typeface (the guidelines recommend Arial/Helvetica >=10pt;
        # `helvet` is the portable Helvetica clone shipped by every TeX distro, so no system font file is
        # needed and the build stays reproducible under Tectonic). 2026-07-05.
        "-V", "linestretch=1.5",
        "-V", "header-includes=\\usepackage{helvet}\\renewcommand{\\familydefault}{\\sfdefault}",
        "-V", "linkcolor=blue",
        "-V", "urlcolor=blue",
        "--metadata", "link-citations=true",
        "-o", str(pdf_path),
    ]
    print(f"[build_paper] pandoc -> {pdf_path}")
    # Tectonic's TeX-package cache goes to D: — C: ran to 0 bytes free on the first-ever compile
    # (2026-07-02, os error 112) and the cache (~hundreds of MB) does not belong on the full system
    # drive. TECTONIC_CACHE_DIR is tectonic's supported cache override; the cache is regenerable.
    env = dict(os.environ)
    env.setdefault("TECTONIC_CACHE_DIR", r"D:\tectonic-cache")
    proc = subprocess.run(cmd, capture_output=True, text=True, cwd=str(REPO), env=env)
    # Surface every warning: a citeproc "reference not found" in the PDF is a grading defect.
    warnings = [ln for ln in (proc.stderr or "").splitlines() if "WARNING" in ln or "Error" in ln]
    for ln in warnings:
        print(f"[pandoc] {ln}", file=sys.stderr)
    if proc.returncode != 0:
        tail = "\n".join((proc.stderr or "").splitlines()[-25:])
        print(f"[build_paper] FAILED (exit {proc.returncode}):\n{tail}", file=sys.stderr)
        return proc.returncode
    size_kb = pdf_path.stat().st_size // 1024
    print(f"[build_paper] OK: {pdf_path} ({size_kb} KB); {len(warnings)} pandoc warning(s)")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Assemble + compile the dissertation PDF.")
    ap.add_argument("--md-only", action="store_true", help="assemble the markdown only (no pandoc)")
    ap.add_argument("--out", type=Path, default=None, help="output PDF path")
    args = ap.parse_args(argv)
    return build(md_only=args.md_only, out=args.out)


if __name__ == "__main__":
    raise SystemExit(main())
