"""σ_D pilot ARCHIVE GENERATOR — train the two fixed rewards across a shared CRN seed set.

Why this exists (the missing GENERATION step for ``scripts/sigma_seed_pilot.py``)
--------------------------------------------------------------------------------
``scripts/sigma_seed_pilot.py`` is the σ_D **analyzer**: it reads the two fixed-reward arms'
per-seed TEST records over a SHARED seed set and measures σ_a/σ_b/σ_D/ρ → the seed-count
decision (the ``n_seeds`` freeze-blocker). But those per-seed TEST records DO NOT EXIST
pre-campaign — they must be GENERATED by training the two baselines across a shared Common
Random Numbers (CRN) seed set and archiving them in the campaign per-seed-record format the
analyzer consumes. This script is that generator.

The two fixed rewards are the H2-RA (``differential_sharpe``) and H2-Tail
(``return_minus_cvar``) canonical baselines (``src/baselines/rewards.py``, ``REWARD_CANON``).
For each shared seed and each reward this:

  1. resolves the SAME three windows the campaign uses (SPLIT C: train 2005-2016 / val 2017-2019 /
     sealed test 2020-2026) via ``run_campaign.resolve_windows`` — synthetic panels degrade
     gracefully to their integer-date clamps;
  2. re-seeds the FULL stack (``set_global_seed``) so the seed set is Common Random Numbers
     across the two arms (the pairing the σ_D pilot's ρ measures);
  3. trains the FIXED SB3-SAC agent (``src/agents/trainer.py::make_agent_trainer``) on the
     TRAIN window at the ``--budget`` step budget (== B*), buffer coupled to the budget;
  4. evaluates the trained policy ONCE on the SEALED TEST leg (``bundle.test_returns``);
  5. archives ONE per-seed record via ``src.orchestration.test_leg.build_test_record`` +
     ``src.io.results.write_run`` under ``<out-dir>/<reward>/<reward>-s{seed}/`` — carrying
     ``arm`` (== the reward key, matching the analyzer's default arm names), ``seed``, and
     ``metrics['test_returns']`` — the EXACT schema ``sigma_seed_pilot`` reads.

This REUSES the campaign trainer + eval + record schema + ``write_run`` (it does NOT
re-architect): the training mirrors ``scripts/learning_curve.py`` and the test archiving
mirrors ``scripts/run_campaign.py::evaluate_winner_on_test`` (the shared ``build_test_record``).

NOT the campaign
----------------
This is a PRE-FREEZE engineering PILOT on the machinery (like ``learning_curve.py``): it runs
two FIXED rewards (no LLM, no search/select/freeze) purely to size ``n_seeds``. No number here
enters the dissertation; it INFORMS the (amendment-gated) seed count. It does not touch the
freeze gate and is safe to run before ``scripts/freeze.py``.

Then FEED the analyzer::

    python scripts/sigma_seed_pilot.py --root <out-dir>

Flags
-----
  --budget     Per-training step budget (== B*, the convergence-pilot's recommendation).
  --n-seeds    Number of SHARED CRN seeds (default 15); seeds are ``0 .. n-1``.
  --out-dir    Archive root the analyzer's ``--root`` points at (default ``outputs/sigma_pilot``).
  --synthetic  Train on a synthetic panel instead of real gold (for the smoke test).
  --device     ``cpu`` | ``cuda`` | ``auto`` (default ``auto``).
  --end        Real-data slice end date (default ``2026-06-30`` — the full dev+eval span).
  --resume     Skip (arm, seed) records already archived (idempotent).
  --gpu        Concurrent training workers (default 1 = the serial loop, unchanged). ``N>=2`` farms
               the (reward, seed) cells across ``N`` spawn workers via the campaign's proven
               ``run_recycling`` device pool — science-neutral (every cell re-seeds the full stack
               itself and writes the same record to the same path; only wall-clock changes).
               Preflighted at ~2.5 GB free RAM per worker (measured ~2.11 GB RSS each).
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np

# The two FIXED rewards the σ_D pilot pairs (H2-RA + H2-Tail); the record ``arm`` is the reward key,
# matching ``sigma_seed_pilot``'s default ``--arm-a``/``--arm-b`` so the analyzer reads them directly.
PILOT_REWARDS: tuple[str, ...] = ("differential_sharpe", "return_minus_cvar")


def _resolve_agent_cfg(budget: int, device: str) -> dict[str, Any]:
    """Build the FIXED agent config at ``budget`` steps (mirrors run_prototype._agent_cfg + the campaign).

    The replay buffer is HARD-capped at the campaign cap (config/campaign.yaml agent.buffer_size, default
    50k), PopArt + the gated ``learning_starts`` on — the campaign numerics. Reuses ``run_prototype._agent_cfg``
    for the hyperparameter defaults (batch/lr/gamma/ent_coef/...) so the pilot agent matches the campaign's,
    then pins the budget/(capped) buffer/device. Without the cap, buffer_size == budget OOMs the 15.6 GB
    laptop at the 1,893-dim obs for budgets >=200k (ADR-025 extended; CLAUDE.md 2026-06-30) — so the σ_D
    pilot trains under the SAME bounded ~0.76 GB replay as the campaign.
    """
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from run_prototype import _agent_cfg  # type: ignore[import-not-found]

    from src.utils.config import load_config

    buffer_cap = int((load_config("campaign").get("agent") or {}).get("buffer_size") or 50000)
    cfg = _agent_cfg(load_config("prototype"), int(budget))
    cfg["train_steps_per_candidate"] = int(budget)
    cfg["buffer_size"] = min(int(budget), buffer_cap)  # capped == campaign replay cap
    cfg["device"] = device
    return cfg


def _resolve_panel_and_windows(
    synthetic: bool, end: str, embargo: int, lookback: int
) -> tuple[Any, dict[str, Any], tuple[int, int], tuple[int, int], tuple[int, int]]:
    """Return ``(panel, panel_descriptor, train_window, val_window, test_window)``.

    Uses ``run_campaign.resolve_windows`` (the SAME three-window construction the headline campaign
    uses) so the pilot's TEST leg is the sealed 2020-2026 span on real gold, and the synthetic panel
    degrades to its integer-date clamps. The dev-phase gold is loaded to the full evaluation end so the
    2020-2026 test window lives in the same panel object (mirrors ``run_headline_campaign``).
    """
    import run_campaign  # type: ignore[import-not-found]

    from src.utils.config import load_config

    inf_cfg = load_config("inference")
    splits = inf_cfg.get("splits", {})

    if synthetic:
        from src.data.synthetic import make_synthetic_panel

        panel = make_synthetic_panel(n_assets=30, n_days=600, seed=0)
        descriptor: dict[str, Any] = {"synthetic": True}
        # The FROZEN 2005-2026 calendar splits collapse a 600-day synthetic panel to degenerate tail
        # windows (resolve_windows clamps everything past the panel end). For the synthetic smoke path we
        # instead carve three proportional, purge-respecting windows on the panel itself (mirroring
        # learning_curve.py's in-panel split): train [lookback, s1) / val [s1+purge, s2) / test [s2+purge, T).
        # The real-gold path below keeps the calendar-based resolve_windows exactly (its clamps are inert
        # on the 5,406-session panel).
        purge = max(int(embargo), int(lookback))
        T = int(panel.T)
        s1 = max(lookback + 1, int(T * 0.55))
        val_start = s1 + purge
        s2 = max(val_start + 1, int(T * 0.75))
        test_start = s2 + purge
        train_window = (lookback, s1)
        val_window = (val_start, s2)
        test_window = (test_start, T)
        return panel, descriptor, train_window, val_window, test_window

    from src.data.loaders import load_gold_panel

    # verify_checksum=True (C2): the σ-pilot trains on the SAME production gold panel as the headline;
    # checksum-verify it against the frozen manifest (mismatch or missing entry fails loud).
    panel = load_gold_panel(phase="development", end=str(end), verify_checksum=True).panel
    descriptor = {
        "synthetic": False, "phase": "development", "end": str(end),
        "on_missing": "liquidate_to_cash",
    }
    train_window, val_window, test_window = run_campaign.resolve_windows(
        panel, lookback, splits, embargo=embargo
    )
    return panel, descriptor, train_window, val_window, test_window


def train_one(
    reward_key: str,
    seed: int,
    *,
    panel: Any,
    env_cfg: Any,
    agent_cfg: dict[str, Any],
    train_window: tuple[int, int],
    val_window: tuple[int, int],
    test_window: tuple[int, int],
    embargo: int,
    lookback: int,
) -> dict[str, Any]:
    """Train the FIXED agent on ``reward_key`` at ``seed``; return the archive record (never raises).

    Mirrors ``run_campaign.evaluate_winner_on_test`` for ONE (reward, seed): re-seed the full stack
    (CRN), build the 3-window bundle, train, touch the SEALED test leg ONCE, and assemble the record
    via the shared ``build_test_record`` (so the schema cannot drift from the campaign's). The record's
    ``arm`` is the reward key. Returns ``{"record": <record>|None, "ok": bool, "error": str|None,
    "seconds": float}`` — a failed cell is reported, never aborts the sweep.
    """
    import hashlib

    from src.baselines.rewards import REWARD_CANON
    from src.env.runner import make_env_builder
    from src.orchestration.test_leg import build_test_record
    from src.utils.seeding import set_global_seed

    out: dict[str, Any] = {"record": None, "ok": False, "error": None, "seconds": 0.0}
    try:
        if reward_key not in REWARD_CANON:
            raise KeyError(f"unknown reward {reward_key!r}; REWARD_CANON has {sorted(REWARD_CANON)}")
        reward_fn = REWARD_CANON[reward_key]

        # CRN: re-seed the FULL stack per seed so the two arms share the SAME seed set (the pairing the
        # σ_D pilot's ρ measures). Same reseeding as evaluate_winner_on_test's test leg.
        set_global_seed(int(seed), deterministic_torch=True)

        builder = make_env_builder(
            panel,
            env_cfg,
            train_window,
            val_window,
            test_window=test_window,
            embargo=embargo,
            lookback=lookback,
        )
        bundle = builder(reward_fn)

        from src.agents.trainer import make_agent_trainer

        train_fn = make_agent_trainer(agent_cfg, int(seed))
        t0 = time.perf_counter()
        policy = train_fn(bundle.train_env())
        test_returns = np.asarray(bundle.test_returns(policy), dtype=float)
        out["seconds"] = round(time.perf_counter() - t0, 2)

        # A FIXED-reward pilot "winner" record so build_test_record carries the same fields the campaign
        # writes; there is no search/select/freeze, so val_fitness is NaN and the source is a comment stub.
        source = f"# sigma_pilot:{reward_key}\n"
        winner = {
            "arm": reward_key,
            "candidate_id": f"{reward_key}-pilot",
            "generation": 0,
            "reward_source": source,
            "reward_source_hash": hashlib.sha256(source.encode("utf-8")).hexdigest(),
            "feedback_block": "",
            "metrics": {"val_fitness": float("nan")},
        }
        record = build_test_record(
            winner=winner,
            arm=reward_key,
            seed=int(seed),
            reward_hash=winner["reward_source_hash"],
            env_fp=f"sigma_pilot:{reward_key}:test[{test_window[0]},{test_window[1]})",
            test_returns=test_returns,
        )
        out["record"] = record
        out["ok"] = True
    except Exception as exc:  # noqa: BLE001 - one failed cell must not abort the sweep
        import traceback

        out["error"] = f"{type(exc).__name__}: {exc}"
        out["traceback"] = traceback.format_exc().splitlines()[-3:]
    return out


# --------------------------------------------------------------------------- #
# Farm mode (--gpu N>=2): the (reward, seed) cells across a spawn-worker pool   #
# --------------------------------------------------------------------------- #
#: Per-worker RAM the farm preflight requires: ~2.11 GB RSS measured per training worker (2026-07-02
#: probe: 1 worker ~55 steps/s, 3 workers ~186 aggregate), rounded up to 2.5 GB for OS/allocator
#: headroom — so ``--gpu 3`` needs ~7.5 GB free BEFORE any child is spawned.
_FARM_GB_PER_WORKER: float = 2.5

#: Fresh worker pools every N cells (``run_recycling``'s RAM-reset cadence, two waves at ``--gpu 3``):
#: pool teardown returns each worker's ENTIRE fragmented SAC-replay heap to the OS, so per-worker RSS
#: cannot creep across a long sweep (the Windows-spawn-safe substitute for ``max_tasks_per_child``).
_FARM_RECYCLE_EVERY: int = 6


def _preflight_farm_ram(n_workers: int) -> None:
    """Fail LOUD before spawning if available RAM cannot hold ``n_workers`` concurrent cells.

    Mirrors ``src.orchestration.parallel.auto_n_gpu``'s psutil sizing, but as a hard GATE with an
    actionable message: a farm that swaps is SLOWER than serial (and a mid-run MemoryError throws
    away hours of training), so refuse to start rather than degrade silently.
    """
    import psutil

    available_gb = psutil.virtual_memory().available / 2**30
    required_gb = _FARM_GB_PER_WORKER * int(n_workers)
    if available_gb < required_gb:
        raise RuntimeError(
            f"[run_sigma_pilot_train] farm preflight: only {available_gb:.1f} GB RAM available, but "
            f"--gpu {int(n_workers)} needs ~{required_gb:.1f} GB ({_FARM_GB_PER_WORKER} GB/worker; "
            f"~2.11 GB RSS measured per training). Free RAM (close applications) or lower --gpu."
        )


def build_cell_specs(
    rewards: tuple[str, ...],
    seeds: list[int],
    *,
    out_dir: str | Path,
    panel_descriptor: dict[str, Any],
    env_cfg: Any,
    agent_cfg: dict[str, Any],
    train_window: tuple[int, int],
    val_window: tuple[int, int],
    test_window: tuple[int, int],
    embargo: int,
    lookback: int,
    done_ids: set[str] | frozenset[str] = frozenset(),
) -> list[dict[str, Any]]:
    """One picklable spec per (reward, seed) cell, in EXACTLY the serial loop's iteration order.

    Reward-major, seed-minor — the same ``for reward: for seed:`` nest the serial path runs — with the
    same resume key (``run_id = f"{reward}-s{seed}"``, skipped when in ``done_ids``) and the same
    per-arm output root, so farming reorders NOTHING but the wall-clock. The panel itself is NOT
    pickled (tens of MB per spec): the worker reloads it from ``panel_descriptor`` via the TEST leg's
    cached ``_load_test_panel`` — deterministic, so every child's panel equals the parent's.
    """
    specs: list[dict[str, Any]] = []
    for reward_key in rewards:
        arm_root = str(Path(out_dir) / reward_key)
        for seed in seeds:
            run_id = f"{reward_key}-s{int(seed)}"
            if run_id in done_ids:
                continue
            specs.append(
                {
                    "run_id": run_id,
                    "arm": reward_key,  # == the reward key (the analyzer's arm name)
                    "seed": int(seed),
                    "arm_root": arm_root,
                    "panel_descriptor": dict(panel_descriptor),
                    "env_cfg": env_cfg,
                    "agent_cfg": dict(agent_cfg),
                    "train_window": list(train_window),
                    "val_window": list(val_window),
                    "test_window": list(test_window),
                    "embargo": int(embargo),
                    "lookback": int(lookback),
                }
            )
    return specs


def _pilot_cell_worker(spec: dict[str, Any]) -> dict[str, Any]:
    """Farm worker: ONE (reward, seed) cell — exactly one serial-loop iteration, in a spawn child.

    Reloads the panel from the picklable descriptor (per-worker cached, the ``test_leg`` pattern), then
    delegates to the SAME :func:`train_one` the serial loop calls — which ``set_global_seed``s the FULL
    stack FIRST (CRN), trains, and builds the record — and writes the SAME record to the SAME
    ``<out_dir>/<reward>/`` location via the atomic ``write_run``. Because every cell re-seeds
    everything at its start and archives to its own run directory, per-cell numerics and records are
    independent of which process (or neighbour cells) ran them — farming is science-neutral
    (wall-clock only). ``spec['device']`` is the pool's device token. Never raises (a failed cell must
    not abort the farm — parity with the serial loop's never-abort contract); returns a light picklable
    summary for the parent's aggregation.
    """
    out: dict[str, Any] = {
        "ok": False, "run_id": spec.get("run_id"), "arm": spec.get("arm"),
        "seed": spec.get("seed"), "error": None, "seconds": 0.0,
    }
    try:
        # The TEST leg's descriptor->panel reload (cached per worker process): a bare
        # {"synthetic": True} descriptor rebuilds make_synthetic_panel(30, 600, seed=0), and the gold
        # descriptor reloads the SAME frozen parquet the parent resolved windows on (the parent already
        # checksum-verified it ONCE this run, so the child skips the re-hash).
        from src.orchestration.test_leg import _load_test_panel

        panel = _load_test_panel(spec["panel_descriptor"])
        res = train_one(
            str(spec["arm"]),
            int(spec["seed"]),
            panel=panel,
            env_cfg=spec["env_cfg"],
            # The pool's device token ('cuda' under --gpu N; 'cpu' under --device cpu) replaces the
            # serial path's --device string; everything else is the parent's agent_cfg verbatim.
            agent_cfg={**spec["agent_cfg"], "device": spec.get("device", "cpu")},
            train_window=tuple(spec["train_window"]),
            val_window=tuple(spec["val_window"]),
            test_window=tuple(spec["test_window"]),
            embargo=int(spec["embargo"]),
            lookback=int(spec["lookback"]),
        )
        out["seconds"] = float(res.get("seconds", 0.0))
        if res["ok"] and res["record"] is not None:
            from src.io.results import write_run

            # Write IN the worker (not the driver) so a farmed run archives INCREMENTALLY like the
            # serial loop: a crash loses at most the in-flight cells and --resume picks up the rest.
            write_run(res["record"], spec["arm_root"])
            out["ok"] = True
        else:
            out["error"] = res.get("error")
    except Exception as exc:  # noqa: BLE001 - one failed cell must not abort the farm (serial parity)
        out["error"] = f"{type(exc).__name__}: {exc}"
    return out


def _summarize_farm(
    results: list[dict[str, Any]], rewards: tuple[str, ...], seeds: list[int]
) -> dict[str, dict[str, Any]]:
    """Fold farmed cell results into the serial path's per-arm summary — order-INDEPENDENTLY.

    Cells are grouped by arm and sorted by seed (the serial iteration order) before folding, so the
    summary (counts, error list, median seconds) is identical no matter the pool's completion order —
    ``run_recycling`` preserves submission order anyway, but the sort makes the aggregation provably
    independent of it. KEEP the folded fields in lockstep with the serial loop's bookkeeping in
    :func:`run_pilot_training`.
    """
    by_arm: dict[str, list[dict[str, Any]]] = {reward_key: [] for reward_key in rewards}
    for res in results:
        by_arm[str(res.get("arm"))].append(res)  # an unknown arm is a bug -> fail loud (KeyError)

    per_arm: dict[str, dict[str, Any]] = {}
    for reward_key in rewards:
        cells = sorted(by_arm[reward_key], key=lambda r: int(r["seed"]))
        written = 0
        failed = 0
        errors: list[str] = []
        seconds: list[float] = []
        for res in cells:
            if res.get("ok"):
                written += 1
                seconds.append(float(res.get("seconds", 0.0)))
            else:
                failed += 1
                errors.append(f"seed {res['seed']}: {res.get('error')}")
                print(
                    f"[run_sigma_pilot_train] {reward_key} seed {res['seed']} FAILED: "
                    f"{res.get('error')}",
                    flush=True,
                )
        per_arm[reward_key] = {
            "written": written, "failed": failed, "n_seeds": len(seeds),
            "seconds_median": float(np.median(seconds)) if seconds else None,
            "errors": errors[:5],
        }
        print(
            f"[run_sigma_pilot_train] {reward_key}: wrote {written}/{len(seeds)} seeds "
            f"(failed {failed})"
            + (f" median {per_arm[reward_key]['seconds_median']:.1f}s/train" if seconds else "")
        )
    return per_arm


def _run_farm(
    rewards: tuple[str, ...],
    seeds: list[int],
    *,
    gpu: int,
    out_dir: Path,
    panel_descriptor: dict[str, Any],
    env_cfg: Any,
    agent_cfg: dict[str, Any],
    train_window: tuple[int, int],
    val_window: tuple[int, int],
    test_window: tuple[int, int],
    embargo: int,
    lookback: int,
    device: str,
    resume: bool,
    runner: Any = None,
) -> dict[str, dict[str, Any]]:
    """Farm the (reward, seed) cells across ``gpu`` device-pooled spawn workers (``--gpu N>=2``).

    Science-neutral vs the serial loop: the SAME cells in the SAME order (:func:`build_cell_specs`),
    the SAME per-cell body (:func:`train_one` re-seeds the full stack first — CRN), the SAME records
    to the SAME paths (``write_run`` in the worker), and a summary folded order-independently from the
    returned results — only wall-clock changes. The farming machinery is the campaign TEST leg's
    proven ``run_recycling`` (``src/orchestration/test_leg.py`` is the reference driver). ``runner``
    is injectable so the orchestration is unit-tested with no spawn / no torch (the test_leg pattern).
    """
    _preflight_farm_ram(int(gpu))

    done_ids: set[str] = set()
    for reward_key in rewards:
        arm_root = out_dir / reward_key
        arm_root.mkdir(parents=True, exist_ok=True)  # parity with the serial loop's per-arm mkdir
        if resume:
            from src.io.results import load_all

            # The serial path's resume key, verbatim: a cell is done iff its record loads from disk.
            done_ids |= {str(r.get("run_id")) for r in load_all(arm_root)}

    specs = build_cell_specs(
        rewards, seeds, out_dir=out_dir, panel_descriptor=panel_descriptor, env_cfg=env_cfg,
        agent_cfg=agent_cfg, train_window=train_window, val_window=val_window,
        test_window=test_window, embargo=embargo, lookback=lookback, done_ids=done_ids,
    )

    if runner is None:  # injectable for the no-spawn unit tests (the test_leg pattern)
        from src.orchestration.parallel import run_recycling as runner

    # SINGLE-device pools only: CPU and CUDA are not bit-identical, so a mixed pool would make a
    # cell's numerics depend on scheduler luck (the campaign TEST leg's rule). --device cpu farms on
    # CPU tokens (a GPU-less smoke); auto/cuda farm on 'cuda' tokens (n_gpu=N, n_cpu=0 — the measured
    # 1->3-worker ~55->~186 steps/s aggregate configuration).
    n_gpu, n_cpu = (0, int(gpu)) if device == "cpu" else (int(gpu), 0)
    print(
        f"[run_sigma_pilot_train] farming {len(specs)} cells across {int(gpu)} workers "
        f"(n_gpu={n_gpu}, n_cpu={n_cpu}, recycle_every={_FARM_RECYCLE_EVERY})",
        flush=True,
    )
    results = runner(
        specs, worker=_pilot_cell_worker, n_gpu=n_gpu, n_cpu=n_cpu,
        recycle_every=_FARM_RECYCLE_EVERY,
    )

    # Re-attribute by position (run_recycling returns results in SUBMISSION order — the contract
    # tests/test_parallel_recycling.py locks): a worker that DIED (OOM/kill) surfaces as the pool's
    # bare {"ok": False, "error": ...} WITHOUT arm/seed, which the summary could not bucket. Spec
    # fields fill the gaps; a worker's own fields (equal by construction) win when present.
    if len(results) != len(specs):
        raise RuntimeError(
            f"farm returned {len(results)} results for {len(specs)} specs — run_recycling's "
            "one-result-per-spec contract is broken"
        )
    attributed = [
        {"arm": s["arm"], "seed": s["seed"], "run_id": s["run_id"], **r}
        for s, r in zip(specs, results)
    ]
    return _summarize_farm(attributed, rewards, seeds)


def run_pilot_training(
    *,
    budget: int,
    n_seeds: int,
    out_dir: str | Path,
    synthetic: bool,
    device: str,
    end: str,
    resume: bool = False,
    rewards: tuple[str, ...] = PILOT_REWARDS,
    gpu: int = 1,
    runner: Any = None,
) -> dict[str, Any]:
    """Train both fixed rewards across the shared CRN seed set ``0..n_seeds-1``, archive per-seed records.

    Writes ``<out_dir>/<reward>/<reward>-s{seed}/record.json`` for each (reward, seed) — the layout
    ``analyze_campaign.load_campaign_records`` walks and ``sigma_seed_pilot`` reads. Returns a summary
    dict (per-arm written/failed counts + timings). ``--resume`` skips (reward, seed) cells already on
    disk (idempotent). ``gpu=1`` (default) is the original serial loop, untouched; ``gpu>=2`` farms the
    cells across a spawn-worker pool (:func:`_run_farm` — same cells, same records, same paths; only
    wall-clock changes). ``runner`` overrides the farm's ``run_recycling`` for no-spawn unit tests.
    """
    from src.io.results import write_run
    from src.utils.config import load_config

    env_cfg = load_config("environment")
    lookback = int(env_cfg["state"]["lookback_days"])
    inf_cfg = load_config("inference")
    embargo = int(inf_cfg.get("splits", {}).get("embargo_trading_days", 21))

    panel, descriptor, train_w, val_w, test_w = _resolve_panel_and_windows(
        synthetic, end, embargo, lookback
    )
    agent_cfg = _resolve_agent_cfg(budget, device)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    seeds = list(range(int(n_seeds)))

    per_arm: dict[str, dict[str, Any]] = {}
    if int(gpu) >= 2:
        # Farm mode: the parent's panel object is dropped here — each worker reloads an identical
        # panel from `descriptor` (see _pilot_cell_worker); windows/configs were resolved on it above.
        per_arm = _run_farm(
            rewards, seeds, gpu=int(gpu), out_dir=out_dir, panel_descriptor=descriptor,
            env_cfg=env_cfg, agent_cfg=agent_cfg, train_window=train_w, val_window=val_w,
            test_window=test_w, embargo=embargo, lookback=lookback, device=device,
            resume=resume, runner=runner,
        )
    else:
        for reward_key in rewards:
            arm_root = out_dir / reward_key
            arm_root.mkdir(parents=True, exist_ok=True)
            done: set[str] = set()
            if resume:
                from src.io.results import load_all

                if arm_root.is_dir():
                    done = {str(r.get("run_id")) for r in load_all(arm_root)}

            written = 0
            failed = 0
            errors: list[str] = []
            seconds: list[float] = []
            for seed in seeds:
                run_id = f"{reward_key}-s{int(seed)}"
                if run_id in done:
                    continue
                res = train_one(
                    reward_key,
                    seed,
                    panel=panel,
                    env_cfg=env_cfg,
                    agent_cfg=agent_cfg,
                    train_window=train_w,
                    val_window=val_w,
                    test_window=test_w,
                    embargo=embargo,
                    lookback=lookback,
                )
                if res["ok"] and res["record"] is not None:
                    write_run(res["record"], arm_root)
                    written += 1
                    seconds.append(float(res["seconds"]))
                else:
                    failed += 1
                    errors.append(f"seed {seed}: {res['error']}")
                    print(f"[run_sigma_pilot_train] {reward_key} seed {seed} FAILED: {res['error']}", flush=True)
            per_arm[reward_key] = {
                "written": written, "failed": failed, "n_seeds": len(seeds),
                "seconds_median": float(np.median(seconds)) if seconds else None,
                "errors": errors[:5],
            }
            print(
                f"[run_sigma_pilot_train] {reward_key}: wrote {written}/{len(seeds)} seeds "
                f"(failed {failed})"
                + (f" median {per_arm[reward_key]['seconds_median']:.1f}s/train" if seconds else "")
            )

    return {
        "out_dir": str(out_dir),
        "budget": int(budget),
        "n_seeds": int(n_seeds),
        "rewards": list(rewards),
        "synthetic": bool(synthetic),
        "device": device,
        "train_window": list(train_w),
        "val_window": list(val_w),
        "test_window": list(test_w),
        "per_arm": per_arm,
    }


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="σ_D pilot archive generator — train the two fixed rewards over a shared CRN seed set.",
    )
    p.add_argument("--budget", type=int, default=50000, help="Per-training step budget (== B*).")
    p.add_argument("--n-seeds", type=int, default=15, help="Number of shared CRN seeds (0..n-1).")
    p.add_argument("--out-dir", default="outputs/sigma_pilot", help="Archive root (analyzer --root).")
    p.add_argument("--synthetic", action="store_true", help="Train on a synthetic panel (smoke).")
    p.add_argument("--device", default="auto", choices=["cpu", "cuda", "auto"], help="Compute device.")
    p.add_argument("--end", default="2026-06-30", help="Real-data slice end date (full dev+eval span).")
    p.add_argument("--resume", action="store_true", help="Skip (arm, seed) records already archived.")
    p.add_argument(
        "--gpu", type=int, default=1,
        help="Concurrent training workers (1 = serial; N>=2 farms cells across N spawn workers, "
             "~2.5 GB free RAM each — preflighted).",
    )
    return p


def main() -> None:
    # Windows consoles default to a legacy codepage (e.g. cp1251) that cannot encode the σ/ρ glyphs
    # this pilot prints; force UTF-8 on the streams so the banner never crashes the run. No-op where
    # reconfigure is unavailable or stdout is already UTF-8. MUST precede parse_args(): ``--help``
    # prints the σ-bearing parser description, so reconfiguring after it crashed --help on cp1251.
    for _stream in (sys.stdout, sys.stderr):
        try:
            _stream.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
        except (AttributeError, ValueError):
            pass

    args = build_parser().parse_args()

    from src.utils.preload import preload

    preload(strict=True)  # pyarrow before torch (real gold parquet ABI guard) — BEFORE any torch import; H2 fail-loud

    print("=" * 72)
    print("[run_sigma_pilot_train] σ_D pilot archive generation (two fixed rewards x CRN seeds)")
    print(f"  rewards  : {list(PILOT_REWARDS)}")
    print(f"  budget   : {args.budget}")
    print(f"  n_seeds  : {args.n_seeds}  (seeds 0..{args.n_seeds - 1})")
    print(f"  panel    : {'synthetic' if args.synthetic else f'real gold dev -> {args.end}'}")
    print(f"  device   : {args.device}")
    print(f"  gpu      : {args.gpu}  ({'farmed via run_recycling' if int(args.gpu) >= 2 else 'serial'})")
    print(f"  out_dir  : {args.out_dir}")
    print("=" * 72)

    summary = run_pilot_training(
        budget=int(args.budget),
        n_seeds=int(args.n_seeds),
        out_dir=args.out_dir,
        synthetic=bool(args.synthetic),
        device=args.device,
        end=str(args.end),
        resume=bool(args.resume),
        gpu=int(args.gpu),
    )

    print("-" * 72)
    print(f"[run_sigma_pilot_train] windows train={summary['train_window']} "
          f"val={summary['val_window']} test={summary['test_window']}")
    total = sum(a["written"] for a in summary["per_arm"].values())
    print(f"[run_sigma_pilot_train] wrote {total} per-seed TEST records -> {summary['out_dir']}")
    print(
        f"[run_sigma_pilot_train] NEXT: python scripts/sigma_seed_pilot.py --root {summary['out_dir']}"
    )


if __name__ == "__main__":
    main()
